defaults: &defaults
  home:
    test: dayi
  admins:
    class_name: "all"
    email: "admin@qq.com"
  users:
    class_name: "User"
  roles:
    class_name: "Role" 
    super_admin: "超级管理员"
    new_buyer: "新买家"
    new_seller: "新卖家"
  permissions:
    super_admin: "管理系统所有资源"
  shops:
    class_name: "Shop"
  products:
    class_name: "Product"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
